name: build

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: my-step
        run: echo "Build will appear in compass"
